MAIN_COLOUR = "#03f982"

MAIN_FRAME_COLOR = "#15bfa5"
MAIN_COLOUR_LABEL_BG = "#35e1eb"
MAIN_COLOUR_LABEL_TEXT = "black"

CANVAS_COLOUR = "white"
FIGURE_COLOUR = "black"
RESULT_COLOUR = "red"
CLIPPER_COLOUR = "blue"

COLUMNS = 26

WINDOW_WIDTH = 1500
WINDOW_HEIGHT = 750

DATA_SITUATION = 1/4
BORDERS_SPACE = 10

DATA_FRAME_WIGHT = WINDOW_WIDTH * DATA_SITUATION - BORDERS_SPACE
DATA_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE

CANVAS_SITUATION = 1 - DATA_SITUATION
CANVAS_WIDTH = WINDOW_WIDTH * CANVAS_SITUATION - 2 * BORDERS_SPACE
CANVAS_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE